build: false

environment:
    matrix:
        - PYTHON: "C:\\Python36"
          PYTHON_VERSION: "3.6.0"
          PYTHON_ARCH: "64"

test_script:
    - "%PYTHON%/python -m unittest discover -s ./cli/src/tests"
